#!/usr/bin/env bash

#ip ro del default
#ip ro add default via {{ host_gateway }} dev {{ ansible_default_ipv4.interface }}
ip ro change default via {{ host_gateway }} dev {{ ansible_default_ipv4.interface }}
ip ro del 10.0.0.0/8

ifconfig {{ tinc_netname }} down
