---

- name: Upgrade all packages to the latest version
  apt:
    update_cache: yes
    cache_valid_time: 86400
    upgrade: yes

- name: Install required packages
  apt:
    name: [
      'aptitude',
      'ca-certificates',
      'ccze',
      'curl',
      'dnsutils',
      'htop',
      'iftop',
      'ncdu',
      'net-tools',
      'nload',
      'screen',
      'sysstat',
      'telnet',
      'vim',
      'wget'
    ]
    state: present
    install_recommends: no
