---

scaleway:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: "{{ lookup('env','TF_VAR_scaleway_private_key_path') }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o ProxyCommand="ssh -o IdentitiesOnly=yes -o IdentityFile=${TF_VAR_scaleway_private_key_path} -W %h:%p root@`./bin/ansible/router_ip.sh`"'
  children:
    node:
    router:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
