---

scaleway:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: "{{ lookup('env','TF_VAR_scaleway_private_key_path') }}"
  children:
    node:
      vars:
        ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o ProxyCommand="ssh -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o IdentityFile=${TF_VAR_scaleway_private_key_path} -W %h:%p root@`./../bin/ansible/router_public_ip.sh`"'
    router:
      vars:
        ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
