---

- name: Ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Pritunl default config
  template:
    src: pritunl.conf
    dest: /etc/pritunl.conf

- name: MongoDB apt
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
    state: present
    filename: mongodb-org-3.6

- name: Pritunl apt
  apt_repository:
    repo: deb http://repo.pritunl.com/stable/apt xenial main
    state: present
    filename: pritunl

- name: Apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

- name: Apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A

- name: Install required packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
    install_recommends: no
    allow_unauthenticated: true
  with_items:
  - mongodb-org
  - pritunl

- systemd:
    enabled: true
    name: mongod.service
    state: started

- systemd:
    enabled: true
    name: pritunl.service
    state: started
